const KEY='clinical-pathway.case-001.v2';
const ROUTES=['home','library','station','review','journey'];
const app=document.querySelector('#app');
const dialog=document.querySelector('#confirm-dialog');
let library,station,review=null;

const fresh=()=>({version:1,attempt:{number:1,status:'not_started',startedAt:null,finishedAt:null,locked:false,confidence:null,revealed:[],current:null,log:[],planDiscussed:false},review:{status:'locked',stage:'self_check',self:{},selfComplete:false,mirror:null,whatif:null,repair:null,confidence:null},history:[]});
function load(){try{const value=JSON.parse(localStorage.getItem(KEY));return value?.version===1?value:fresh()}catch{return fresh()}}
let state=load();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const route=()=>{const r=location.hash.replace(/^#/,'')||'home';return ROUTES.includes(r)?r:'home'};
function go(r){location.hash=r}
function reviewUnlocked(){return state.attempt.status==='finished'&&state.review.status!=='locked'}
function navItem(id,label,current){if(id==='review'&&!reviewUnlocked())return `<span class="locked" aria-disabled="true">${label}</span>`;return `<a href="#${id}" ${id===current?'aria-current="page"':''}>${label}</a>`}
function header(current){return `<header class="header"><div class="header-inner"><a class="brand" href="#home"><span class="brand-mark" aria-hidden="true">CP</span><span>Clinical Pathway</span></a><nav class="nav" aria-label="Primary navigation">${navItem('home','Home',current)}${navItem('library','Library',current)}${navItem('station','Station',current)}${navItem('review','Review',current)}${navItem('journey','Journey',current)}</nav></div></header>`}
const liveHeader=()=>`<header class="live-header"><div class="header-inner"><div class="brand"><span class="brand-mark" aria-hidden="true">CP</span><span>Clinical Pathway</span></div><div class="live-state"><span>Station 001</span><strong>Live attempt</strong></div></div></header>`;
const footer=()=>`<footer class="footer"><div class="footer-inner">Clinical Pathway supports clinical exam practice. It does not replace clinical judgement, supervision or local protocols.</div></footer>`;
function shell(content,current,{live=false}={}){return `<div class="shell">${live?liveHeader():header(current)}<main id="app-main">${content}</main>${live?'':footer()}</div>`}
function nextMove(){if(state.attempt.status==='in_progress')return['Return to live station','station','Your current attempt is still open.'];if(state.attempt.status==='finished'&&state.review.status!=='completed')return['Begin Review','review','Your attempt is locked. Start with Self-check.'];if(state.review.status==='completed')return[state.review.repair?'Open retry plan':'Open Journey','journey',state.review.repair||'Review the pathway and choose the next useful move.'];return['Start Station 001','station','Read the candidate information before the patient encounter begins.']}
function renderHome(){const [label,target,detail]=nextMove();return shell(`<section class="room"><div class="home-grid grid"><div><p class="room-label">Home</p><h1>Practise the station.<br>Understand the logic.</h1><p class="lead">Speak the run, reveal the encounter one step at a time, then examine the weak point after you finish.</p><div class="actions"><button class="button" data-go="${target}">${label}</button><a class="button secondary" href="#library">Open Library</a></div></div><aside class="panel"><p class="kicker">Next useful move</p><h2>${label}</h2><p>${detail}</p><dl class="meta"><div><dt>Phase</dt><dd>1 · Keep the patient safe</dd></div><div><dt>Pattern</dt><dd>Chest pain</dd></div><div><dt>Station</dt><dd>001 · ${statusText()}</dd></div></dl></aside></div></section>`,'home')}
function statusText(){if(state.attempt.status==='in_progress')return'Attempt in progress';if(state.review.status==='completed')return'Review completed';if(state.attempt.status==='finished')return'Review ready';return'Ready to start'}
function renderLibrary(){const phases=library.phases.map(p=>`<section class="panel phase ${p.status!=='active'?'phase-preview':''}"><div class="phase-head"><div><p class="kicker">Phase ${p.number}</p><h2>${esc(p.title)}</h2><p>${esc(p.confidence_target)}</p></div><strong>${p.status==='active'?'Active pathway':'Pathway preview'}</strong></div>${p.patterns.map(pattern=>`<div class="pattern"><p class="kicker">Pattern</p><h3>${esc(pattern.title)}</h3><p>${esc(pattern.training_focus)}</p>${pattern.stations.map(s=>`<article class="station-card"><div><p>Station ${s.station_number} · ${esc(s.station_type)}</p><h3>${esc(s.title)}</h3><small>Available for a blind attempt. Clinical answers remain inside the locked Review.</small></div><button class="button" data-go="station">${state.attempt.status==='in_progress'?'Continue':'Open station'}</button></article>`).join('')}</div>`).join('')}</section>`).join('');return shell(`<section class="room"><div class="heading-row"><div><p class="room-label">Library</p><h1>Phase → Pattern → Station</h1></div><p class="lead">Choose the training position without seeing the answer.</p></div>${phases}</section>`,'library')}
function readingView(){const c=station.station_card;return shell(`<section class="room"><div class="heading-row"><div><p class="room-label">Station 001</p><h1>Reading screen</h1></div><p class="lead">The patient opening remains hidden until you start.</p></div><div class="reading grid"><article class="panel candidate-card"><h2>${esc(c.heading)}</h2><ul>${c.candidate_information.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="tasks"><h3>${esc(c.tasks_heading)}</h3><ol>${c.tasks.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></article><aside class="panel focus-card"><p class="kicker">${esc(station.reading_time_plan.label)}</p><ol>${station.reading_time_plan.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><fieldset><legend>Confidence before this attempt</legend><div class="confidence">${['Low','Developing','Ready'].map(x=>`<label class="pill"><input type="radio" name="confidence-before" value="${x}" ${state.attempt.confidence===x?'checked':''}><span>${x}</span></label>`).join('')}</div></fieldset><button class="button safe" data-action="start">Start station</button></aside></div></section>`,'station')}
function currentResponse(){const cur=state.attempt.current;if(!cur)return'';return `<p class="speaker">${esc(cur.speaker)}</p><blockquote>${esc(cur.text)}</blockquote>`}
function liveView(){const revealed=new Set(state.attempt.revealed);const actionButtons=station.reveal_actions.map(a=>`<button class="button secondary" data-reveal="${a.id}" ${revealed.has(a.id)?'disabled':''}>${esc(a.label)}</button>`).join('');const responseAction=station.plan_gate.response_action;const responseShown=revealed.has(responseAction.id);const log=state.attempt.log.map(x=>`<li><strong>${esc(x.label)}</strong><p><span class="speaker">${esc(x.speaker)}:</span> ${esc(x.text)}</p></li>`).join('');return shell(`<section class="live-room"><div class="heading-row"><div><p class="room-label">Station 001 · Attempt ${state.attempt.number}</p><h1>Live encounter</h1></div><p class="lead">Speak your questions aloud, then reveal only the information you requested.</p></div><div class="live-grid"><section class="panel response" aria-live="polite"><p class="kicker">Current response</p>${currentResponse()}</section><section class="panel ask"><p class="kicker">Ask or request</p><h2>Choose a broad area</h2><div class="reveal-grid">${actionButtons}</div></section><aside class="panel log"><p class="kicker">Encounter log</p><h2>What has been revealed</h2><ol class="log-list">${log}</ol></aside><section class="panel plan"><p class="kicker">Management discussion</p>${state.attempt.planDiscussed?`<h2>Plan discussion reached</h2><p>David's response is now available as a separate reveal.</p><button class="button secondary" data-reveal="${responseAction.id}" ${responseShown?'disabled':''}>${esc(responseAction.label)}</button>`:`<h2>Keep the plan hidden until you have spoken it</h2><p>Use this only after you have explained your concern and management plan aloud.</p><button class="button" data-action="plan">${esc(station.plan_gate.button_label)}</button>`}</section><section class="panel finish"><div><p class="kicker">Attempt control</p><h2>Finish only when your spoken run is complete</h2><p>Finishing locks all reveals and unlocks Review.</p></div><button class="button danger" data-action="finish-request">${esc(station.finish_action.button_label)}</button></section></div></section>`,'station',{live:true})}
function lockedStation(){return shell(`<section class="room"><div class="panel locked-view"><p class="room-label">Station 001</p><h1>Attempt locked</h1><p class="lead">The encounter cannot be changed after Finish station.</p><div class="actions" style="justify-content:center"><button class="button" data-go="review">Begin Review</button><button class="button secondary" data-go="journey">Open Journey</button></div></div></section>`,'station')}
function renderStation(){if(state.attempt.status==='not_started')return readingView();if(state.attempt.status==='in_progress')return liveView();return lockedStation()}
function reviewLocked(){return shell(`<section class="room"><div class="panel locked-view"><p class="room-label">Review</p><h1>Review is locked</h1><p class="lead">Finish Station 001 before any answer-bearing teaching is loaded.</p><button class="button" data-go="station">Open Station</button></div></section>`,'review')}
function stageNav(){return `<nav class="panel stage-nav" aria-label="Review stages"><ol>${review.stage_order.map((id,i)=>{const s=review.stages.find(x=>x.id===id);const disabled=!state.review.selfComplete&&id!=='self_check';return `<li><button data-stage="${id}" ${disabled?'disabled':''} aria-current="${state.review.stage===id}">${i+1}. ${esc(s.label)}</button></li>`}).join('')}</ol></nav>`}
const choice=(name,value,label,checked=false,attrs='')=>`<label class="pill"><input type="radio" name="${name}" value="${esc(value)}" ${checked?'checked':''} ${attrs}><span>${esc(label)}</span></label>`;
function stageSelf(s){const answered=Object.keys(state.review.self).length;const all=answered===s.items.length;return `<p>${esc(s.intro)}</p>${s.items.map(item=>`<div class="self-item"><h3>${esc(item.text)}</h3><div class="choice-row">${s.choices.map(v=>choice(`self-${item.id}`,v,v,state.review.self[item.id]===v,`data-self="${item.id}"`)).join('')}</div></div>`).join('')}<p><strong>${answered} of ${s.items.length}</strong> marked</p><button class="button" data-action="self-complete" ${all?'':'disabled'}>Continue to Safety mirror</button>`}
function stageSafety(s){return `<p>${esc(s.intro)}</p>${s.profiles.map(p=>`<label class="profile"><input type="radio" name="mirror" value="${p.id}" ${state.review.mirror===p.id?'checked':''} data-mirror><strong>${esc(p.label)}</strong><p>${esc(p.text)}</p></label>`).join('')}${nextButton('what_changed','Continue to What changed')}`}
function stageChanged(s){return `<p>${esc(s.intro)}</p>${s.checkpoints.map(c=>`<div class="checkpoint"><p class="kicker">${esc(c.step)}</p><p>${esc(c.text)}</p></div>`).join('')}<div class="notice"><strong>${esc(s.logic_prompt)}</strong></div>${nextButton('safe_version','Continue to Safe version')}`}
function stageSafe(s){return `<p>${esc(s.intro)}</p><div class="model">${esc(s.model_speech)}</div><h3>Safe sequence</h3><ol>${s.safe_sequence.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Recovery sentence</h3><p class="model">${esc(s.recovery_sentence)}</p><h3>Focused handover</h3><p>${esc(s.handover)}</p>${nextButton('thinking_traps','Continue to Thinking traps')}`}
function stageTraps(s){return `<p>${esc(s.intro)}</p>${s.traps.map(t=>`<div class="trap"><h3>${esc(t.title)}</h3><p>${esc(t.text)}</p></div>`).join('')}${nextButton('what_if_paths','Continue to What-if paths')}`}
function stageWhatIf(s){const selected=s.paths.find(p=>p.id===state.review.whatif);return `<p>${esc(s.intro)}</p>${s.paths.map(p=>`<button class="button secondary" style="margin:0 8px 10px 0" data-whatif="${p.id}">${esc(p.prompt)}</button>`).join('')}${selected?`<div class="whatif"><h3>${esc(selected.prompt)}</h3><p>${esc(selected.response)}</p></div>`:''}${nextButton('try_again','Continue to Try again')}`}
function stageTry(s){return `<p>${esc(s.intro)}</p>${s.repair_options.map(o=>`<label class="repair"><input type="radio" name="repair" value="${o.id}" ${state.review.repair===o.id?'checked':''} data-repair data-task="${esc(o.task)}"><strong>${esc(o.label)}</strong><p>${esc(o.task)}</p></label>`).join('')}<h3>Practice ladder</h3><ol>${s.practice_ladder.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${nextButton('confidence_after_review','Continue to Confidence')}`}
function stageConfidence(s){return `<p>${esc(s.intro)}</p><div class="choice-row">${s.choices.map(c=>choice('confidence-after',c.id,c.label,state.review.confidence===c.id,'data-confidence-after')).join('')}</div><button class="button safe" data-action="review-complete" ${state.review.confidence?'':'disabled'}>Complete Review</button>`}
function nextButton(id,label){return `<div class="actions" style="margin-top:24px"><button class="button" data-stage="${id}">${label}</button></div>`}
function renderReviewStage(){const s=review.stages.find(x=>x.id===state.review.stage);let body='';if(s.id==='self_check')body=stageSelf(s);if(s.id==='safety_mirror')body=stageSafety(s);if(s.id==='what_changed')body=stageChanged(s);if(s.id==='safe_version')body=stageSafe(s);if(s.id==='thinking_traps')body=stageTraps(s);if(s.id==='what_if_paths')body=stageWhatIf(s);if(s.id==='try_again')body=stageTry(s);if(s.id==='confidence_after_review')body=stageConfidence(s);return `<article class="panel stage"><p class="kicker">Review stage</p><h2>${esc(s.label)}</h2>${body}</article>`}
async function renderReview(){if(!reviewUnlocked())return reviewLocked();if(!review)review=await fetch('./assets/data/case-001/review.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Review data could not load');return r.json()});return shell(`<section class="room"><div class="heading-row"><div><p class="room-label">Review</p><h1>Stage the learning</h1></div><p class="lead">Only one main stage is open. Self-check comes first.</p></div>${state.review.status==='completed'?'<div class="notice" style="margin-bottom:20px"><strong>Review complete.</strong> Your next action is shown in Journey.</div>':''}<div class="review-grid">${stageNav()}${renderReviewStage()}</div></section>`,'review')}
function renderJourney(){const a=state.attempt.status==='finished';const r=state.review.status==='completed';const retry=Boolean(state.review.repair);const nodes=[['Phase','Phase 1 · Keep the patient safe',true],['Pattern','Chest pain',true],['Station','Station 001',true],['Attempt',a?'Attempt locked':'Attempt not finished',a],['Review',r?'Review completed':a?'Review ready':'Review locked',r],['Retry',retry?state.review.repair:'No retry selected',retry],['Next action',r?(retry?'Retry the selected segment':'Revisit Station 001 later'):'Complete the current pathway',false]];return shell(`<section class="room"><div class="heading-row"><div><p class="room-label">Journey</p><h1>Your professional pathway</h1></div><p class="lead">Phase, pattern, station, attempt, review, retry and next action.</p></div><div class="grid" style="grid-template-columns:minmax(0,1fr) minmax(280px,.45fr)"><div class="path">${nodes.map((n,i)=>`<div class="node ${n[2]?'done':i===nodes.length-1?'next':'current'}"><span class="dot" aria-hidden="true"></span><div class="node-body"><p>${n[0]}</p><h2>${esc(n[1])}</h2></div></div>`).join('')}</div><aside class="panel"><p class="kicker">Next action</p><h2>${r?(retry?'Practise the selected weak segment':'Return later for spaced practice'):a?'Complete Review':'Finish the Station'}</h2><p>${state.review.repair||'Keep the pathway moving one completed step at a time.'}</p><div class="actions"><button class="button" data-go="${r&&retry?'station':a?'review':'station'}">${r&&retry?'Start retry':a?'Open Review':'Open Station'}</button></div></aside></div></section>`,'journey')}
async function render(){let r=route();if(state.attempt.status==='in_progress'&&r!=='station'){history.replaceState(null,'','#station');r='station'}app.setAttribute('aria-busy','true');try{let html;if(r==='home')html=renderHome();if(r==='library')html=renderLibrary();if(r==='station')html=renderStation();if(r==='review')html=await renderReview();if(r==='journey')html=renderJourney();app.innerHTML=html;document.querySelector('h1')?.focus({preventScroll:true})}catch(e){app.innerHTML=shell(`<section class="room"><div class="panel"><h1>Prototype could not load</h1><p>${esc(e.message)}</p></div></section>`,r)}finally{app.setAttribute('aria-busy','false')}}
function reveal(id){if(state.attempt.status!=='in_progress'||state.attempt.revealed.includes(id))return;const item=[...station.reveal_actions,station.plan_gate.response_action].find(x=>x.id===id);if(!item||id==='response_to_plan'&&!state.attempt.planDiscussed)return;state.attempt.revealed.push(id);state.attempt.current={speaker:item.speaker,text:item.response};state.attempt.log.push({label:item.label,speaker:item.speaker,text:item.response});save();render()}
function start(){state.attempt.status='in_progress';state.attempt.startedAt=new Date().toISOString();state.attempt.current={speaker:station.opening_line.speaker,text:station.opening_line.text};state.attempt.log=[{label:'Patient opening',speaker:station.opening_line.speaker,text:station.opening_line.text}];save();render()}
function finish(){state.attempt.status='finished';state.attempt.finishedAt=new Date().toISOString();state.attempt.locked=true;state.attempt.current=null;state.review.status='ready';state.review.stage='self_check';save();go('review')}
app.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.dataset.go){e.preventDefault();go(t.dataset.go)}if(t.dataset.reveal)reveal(t.dataset.reveal);if(t.dataset.action==='start')start();if(t.dataset.action==='plan'){state.attempt.planDiscussed=true;state.attempt.log.push({label:'Plan discussion',speaker:'Station',text:'Management discussion reached. David can now respond to your plan.'});save();render()}if(t.dataset.action==='finish-request')dialog.showModal();if(t.dataset.action==='self-complete'){state.review.selfComplete=true;state.review.status='in_progress';state.review.stage='safety_mirror';save();render()}if(t.dataset.stage){if(state.review.selfComplete||t.dataset.stage==='self_check'){state.review.stage=t.dataset.stage;save();render()}}if(t.dataset.whatif){state.review.whatif=t.dataset.whatif;save();render()}if(t.dataset.action==='review-complete'){state.review.status='completed';save();go('journey')}});
app.addEventListener('change',e=>{const i=e.target;if(i.name==='confidence-before'){state.attempt.confidence=i.value;save()}if(i.dataset.self){state.review.self[i.dataset.self]=i.value;save();render()}if(i.dataset.mirror!==undefined){state.review.mirror=i.value;save()}if(i.dataset.repair!==undefined){state.review.repair=i.dataset.task;save()}if(i.dataset.confidenceAfter!==undefined){state.review.confidence=i.value;save();render()}});
dialog.addEventListener('close',()=>{if(dialog.returnValue==='finish')finish()});
window.addEventListener('hashchange',render);
Promise.all([fetch('./assets/data/library.json',{cache:'no-store'}).then(r=>r.json()),fetch('./assets/data/case-001/station.json',{cache:'no-store'}).then(r=>r.json())]).then(([l,s])=>{library=l;station=s;if(!location.hash)history.replaceState(null,'','#home');render()}).catch(e=>{app.innerHTML=`<main class="room"><div class="panel"><h1>Prototype could not load</h1><p>${esc(e.message)}</p></div></main>`});
